### ISSUE TITLE
add variable metadata to README

### ISSUE THREAD

**Issue by katiejolly** [mggg/ohio-precincts#3]
We need an explanation of what each variable means so that people can confidently use our data

**Comment by katiejolly** [comment]
Add prefixes for the election cycle

**Comment by ykelly** [comment]
need to find US senate results and join to current data

**Comment by katiejolly** [comment]
found senate results on [openelections](https://raw.githubusercontent.com/openelections/openelections-data-oh/master/2016/20161108__oh__general__precinct.csv)

**Comment by ykelly** [comment]
updated metadata for president, governor, and senator results
